"use server"

import { createClient } from "@/lib/supabase/server"
import { revalidatePath } from "next/cache"
import { sendBookingConfirmation, sendReviewRequest } from "@/lib/actions/whatsapp"

export type Booking = {
  id: string
  booking_number: string
  customer_id: string | null
  customer_name: string
  customer_phone: string
  outlet: string
  booking_date: string
  time_slot: string
  table_zone: string | null
  experience_type: string
  package_id: string | null
  package_name: string | null
  num_people: number
  status: string
  payment_status: string
  base_amount: number
  add_ons_amount: number
  total_amount: number
  amount_paid: number
  notes: string | null
  special_request: string | null
  created_at: string
}

export async function getBooking(id: string) {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("bookings")
    .select("*")
    .eq("id", id)
    .single()
  if (error) throw error
  return data as Booking
}

export async function getBookings(filters?: {
  outlet?: string
  status?: string
  date?: string
}) {
  const supabase = await createClient()
  let query = supabase
    .from("bookings")
    .select("*")
    .order("booking_date", { ascending: false })
    .order("created_at", { ascending: false })

  if (filters?.outlet && filters.outlet !== "all") {
    query = query.eq("outlet", filters.outlet)
  }
  if (filters?.status && filters.status !== "all") {
    query = query.eq("status", filters.status)
  }
  if (filters?.date) {
    query = query.eq("booking_date", filters.date)
  }

  const { data, error } = await query
  if (error) throw error
  return data as Booking[]
}

export async function getTodayBookings(outlet?: string) {
  const supabase = await createClient()
  const today = new Date().toISOString().split("T")[0]

  let query = supabase
    .from("bookings")
    .select("*")
    .eq("booking_date", today)
    .order("time_slot", { ascending: true })

  if (outlet && outlet !== "all") {
    query = query.eq("outlet", outlet)
  }

  const { data, error } = await query
  if (error) throw error
  return data as Booking[]
}

export async function createBooking(booking: {
  customer_name: string
  customer_phone: string
  outlet: string
  booking_date: string
  time_slot: string
  table_zone?: string
  experience_type: string
  package_id?: string
  package_name?: string
  num_people?: number
  base_amount: number
  add_ons_amount?: number
  total_amount: number
  notes?: string
  special_request?: string
}) {
  const supabase = await createClient()

  // Find or create the customer by phone (upsert - phone has a unique
  // constraint, see migration 006). Previously this only ever looked up an
  // existing customer and silently left customer_id null for anyone new.
  const { data: customer, error: customerError } = await supabase
    .from("customers")
    .upsert(
      {
        name: booking.customer_name,
        phone: booking.customer_phone,
        city: booking.outlet.toLowerCase().includes("vadodara") ? "Vadodara" : "Surat",
      },
      { onConflict: "phone", ignoreDuplicates: false }
    )
    .select("id")
    .single()

  if (customerError) throw customerError

  const { data, error } = await supabase
    .from("bookings")
    .insert({
      ...booking,
      booking_number: "", // auto-generated by trigger
      customer_id: customer?.id || null,
      status: "confirmed",
      payment_status: "pending",
      add_ons_amount: booking.add_ons_amount || 0,
      num_people: booking.num_people || 2,
    })
    .select()
    .single()

  if (error) throw error

  if (customer?.id) {
    await supabase.rpc("update_customer_stats", { p_customer_id: customer.id })
  }

  // Best-effort - a failed WhatsApp send must never fail booking creation.
  sendBookingConfirmation({
    customer_name: booking.customer_name,
    customer_phone: booking.customer_phone,
    outlet: booking.outlet,
    booking_date: booking.booking_date,
    time_slot: booking.time_slot,
    package_name: booking.package_name,
    total_amount: booking.total_amount,
  }).catch((err) => console.error("sendBookingConfirmation failed", err))

  revalidatePath("/protected/bookings")
  revalidatePath("/protected/dashboard")
  return data
}

export async function updateBookingStatus(id: string, status: string) {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("bookings")
    .update({ status })
    .eq("id", id)
    .select("customer_name, customer_phone, outlet")
    .single()

  if (error) throw error

  if (status === "completed" && data) {
    sendReviewRequest({
      customer_name: data.customer_name,
      customer_phone: data.customer_phone,
      outlet: data.outlet,
    }).catch((err) => console.error("sendReviewRequest failed", err))
  }

  revalidatePath("/protected/bookings")
  revalidatePath("/protected/dashboard")
}

export async function updatePaymentStatus(id: string, payment_status: string, amount_paid?: number) {
  const supabase = await createClient()
  const updates: Record<string, unknown> = { payment_status }
  if (amount_paid !== undefined) updates.amount_paid = amount_paid

  const { error } = await supabase
    .from("bookings")
    .update(updates)
    .eq("id", id)

  if (error) throw error
  revalidatePath("/protected/bookings")
  revalidatePath("/protected/invoices")
}

export async function deleteBooking(id: string) {
  const supabase = await createClient()
  const { error } = await supabase.from("bookings").delete().eq("id", id)
  if (error) throw error
  revalidatePath("/protected/bookings")
  revalidatePath("/protected/dashboard")
}

export async function getBookingsByWeek(startDate: string, endDate: string, outlet?: string) {
  const supabase = await createClient()
  let query = supabase
    .from("bookings")
    .select("*")
    .gte("booking_date", startDate)
    .lte("booking_date", endDate)
    .order("booking_date", { ascending: true })
    .order("time_slot", { ascending: true })

  if (outlet && outlet !== "all") {
    query = query.eq("outlet", outlet)
  }

  const { data, error } = await query
  if (error) throw error
  return data as Booking[]
}

export async function getBookingStats(outlet?: string) {
  const supabase = await createClient()
  const today = new Date().toISOString().split("T")[0]

  let todayQ = supabase
    .from("bookings")
    .select("total_amount, status, payment_status, outlet")
    .eq("booking_date", today)

  let monthQ = supabase
    .from("bookings")
    .select("total_amount, outlet")
    .gte("booking_date", new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().split("T")[0])

  if (outlet && outlet !== "all") {
    todayQ = todayQ.eq("outlet", outlet)
    monthQ = monthQ.eq("outlet", outlet)
  }

  const [todayRes, monthRes] = await Promise.all([todayQ, monthQ])

  const todayBookings = todayRes.data || []
  const monthBookings = monthRes.data || []

  return {
    todayCount: todayBookings.length,
    todayRevenue: todayBookings
      .filter((b) => b.payment_status === "paid")
      .reduce((sum, b) => sum + (b.total_amount || 0), 0),
    monthRevenue: monthBookings.reduce((sum, b) => sum + (b.total_amount || 0), 0),
    confirmedToday: todayBookings.filter((b) => b.status === "confirmed").length,
  }
}
