"use server"

import { createClient } from "@/lib/supabase/server"
import { revalidatePath } from "next/cache"

export type Invoice = {
  id: string
  invoice_number: string
  booking_id: string | null
  customer_id: string | null
  customer_name: string
  customer_phone: string | null
  outlet: string | null
  subtotal: number
  discount: number
  tax: number
  total_amount: number
  amount_paid: number
  payment_status: string
  payment_method: string | null
  notes: string | null
  due_date: string | null
  created_at: string
}

export async function getInvoice(id: string) {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("invoices")
    .select("*")
    .eq("id", id)
    .single()
  if (error) throw error
  return data as Invoice
}

export async function createInvoiceFromBooking(bookingId: string) {
  const supabase = await createClient()

  // Check if invoice already exists for this booking
  const { data: existing } = await supabase
    .from("invoices")
    .select("id")
    .eq("booking_id", bookingId)
    .maybeSingle()

  if (existing) return existing.id

  // Fetch the booking
  const { data: booking, error: bErr } = await supabase
    .from("bookings")
    .select("*")
    .eq("id", bookingId)
    .single()

  if (bErr || !booking) throw new Error("Booking not found")

  const { data, error } = await supabase
    .from("invoices")
    .insert({
      invoice_number: "",
      booking_id: bookingId,
      customer_id: booking.customer_id || null,
      customer_name: booking.customer_name,
      customer_phone: booking.customer_phone,
      outlet: booking.outlet,
      subtotal: booking.total_amount,
      discount: 0,
      tax: 0,
      total_amount: booking.total_amount,
      amount_paid: booking.amount_paid || 0,
      payment_status: booking.payment_status || "pending",
      payment_method: null,
      notes: booking.notes || null,
    })
    .select("id")
    .single()

  if (error) throw error
  revalidatePath("/protected/invoices")
  return data.id
}

export async function getInvoices(filters?: {
  status?: string
  outlet?: string
}) {
  const supabase = await createClient()
  let query = supabase
    .from("invoices")
    .select("*")
    .order("created_at", { ascending: false })

  if (filters?.status && filters.status !== "all") {
    query = query.eq("payment_status", filters.status)
  }
  if (filters?.outlet && filters.outlet !== "all") {
    query = query.eq("outlet", filters.outlet)
  }

  const { data, error } = await query
  if (error) throw error
  return data as Invoice[]
}

export async function createInvoice(invoice: {
  booking_id?: string
  customer_id?: string
  customer_name: string
  customer_phone?: string
  outlet?: string
  subtotal: number
  discount?: number
  tax?: number
  total_amount: number
  payment_method?: string
  notes?: string
  due_date?: string
}) {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("invoices")
    .insert({
      ...invoice,
      invoice_number: "", // auto-generated by trigger
      discount: invoice.discount || 0,
      tax: invoice.tax || 0,
      amount_paid: 0,
      payment_status: "pending",
    })
    .select()
    .single()

  if (error) throw error
  revalidatePath("/protected/invoices")
  return data
}

export async function recordPayment(
  invoiceId: string,
  amount: number,
  method: string,
  ref?: string
) {
  const supabase = await createClient()

  const { data: invoice } = await supabase
    .from("invoices")
    .select("total_amount, amount_paid")
    .eq("id", invoiceId)
    .single()

  if (!invoice) throw new Error("Invoice not found")

  const newPaid = (invoice.amount_paid || 0) + amount
  const status =
    newPaid >= invoice.total_amount
      ? "paid"
      : newPaid > 0
      ? "partial"
      : "pending"

  await supabase.from("invoices").update({
    amount_paid: newPaid,
    payment_status: status,
    payment_method: method,
  }).eq("id", invoiceId)

  await supabase.from("payment_transactions").insert({
    invoice_id: invoiceId,
    amount,
    payment_method: method,
    transaction_ref: ref || null,
  })

  revalidatePath("/protected/invoices")
}

export async function getInvoiceStats(outlet?: string) {
  const supabase = await createClient()
  let query = supabase
    .from("invoices")
    .select("total_amount, amount_paid, payment_status, outlet")

  if (outlet && outlet !== "all") {
    query = query.eq("outlet", outlet)
  }

  const { data, error } = await query
  if (error) throw error
  const invoices = data || []

  return {
    total: invoices.length,
    totalRevenue: invoices.reduce((s, i) => s + (i.total_amount || 0), 0),
    totalCollected: invoices.reduce((s, i) => s + (i.amount_paid || 0), 0),
    pending: invoices.filter((i) => i.payment_status === "pending").length,
    partial: invoices.filter((i) => i.payment_status === "partial").length,
    paid: invoices.filter((i) => i.payment_status === "paid").length,
  }
}
